# This toolchain file was generated by Gradle to support NDK versions r14 and below.
include(/Users/heshiqi/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake)
set(CMAKE_SYSTEM_VERSION 1)
